### ISSUE TITLE
Breakpoints missing/misbehave on Angular and Chrome Debug Extension

### ISSUE THREAD

**Issue by JosepAlacid** [microsoft/vscode-chrome-debug#950]
Breakpoints misbehave or get ignored when any change is done on Angular 8.2 code.
Same project don't show this issue if I install previous version of VSCode.

- VSCode Version: 1.40.0
- OS Version: Win 10

Steps to Reproduce:

1. Start an Angular debugging session
2. Add breakpoints.
3. Live reload any changes.

Does this issue occur when all extensions are disabled?: Yes, except -obviusly- chrome debug

**Comment by JosepAlacid** [comment]
Just read your request when I was here to add this info from the Debug Console each time I run my projects:
```
Error: Set breakpoints request timed out
    at Timeout._onTimeout (c:\Users\josep\.vscode\extensions\msjsdiag.debugger-for-chrome-4.12.2\node_modules\vscode-chrome-debug-core\out\src\utils.js:96:24)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```
I'm on  `trace: true`. I will upload the log and the sourcemaps resolution in a while!.

**Comment by JosepAlacid** [comment]
Here is the scripts result:
[scripts.txt](https://github.com/microsoft/vscode-chrome-debug/files/3912690/scripts.txt)

And here the trace log file:
[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-chrome-debug/files/3912741/vscode-chrome-debug.txt)

**Comment by roblourens** [comment]
I'm not sure what went wrong becuase it looks like the sourcemaps were resolved and the breakpoint was resolved correctly each time a reload happened.

**Comment by steveja42** [comment]
I am seeing a similar bug.  Breakpoints set before I start the debugger are hit, but once the debugger is started any changes to breakpoints don't have any effect.  If I click a line the red dot appears but it won't get hit, same with toggling a breakpoint off, the red dot disappears but it still gets hit. I am debugging a react app made with create-react-app on windows 10 using launch chrome against localhost and I don't see any error messages
[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-chrome-debug/files/3914605/vscode-chrome-debug.txt)
.

**Comment by roblourens** [comment]
That one looks ok too. Can you share the app?

**Comment by steveja42** [comment]
The breakpoints are working as expected now . Not sure why.

**Comment by JosepAlacid** [comment]
Every now and then I get the following message on VSCode Debug Console:
`Error: Set breakpoints request timed out
    at Timeout._onTimeout (c:\Users\user\.vscode\extensions\msjsdiag.debugger-for-chrome-4.12.3\node_modules\vscode-chrome-debug-core\out\src\utils.js:96:24)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)`

**Comment by filipemcg** [comment]
Hey @JosepAlacid, not sure if you are still having this issue but if you do please pay special attention to the **webRoot**.

A safe way to make sure that the **webRoot** is correctly setup is to have the **.vscode/launch.json** file in the same dir of the root of you angular project:
```
.
├── angular.json
├── .editorconfig
├── .gitignore
├── karma.conf.js
├── package.json
├── package-lock.json
├── src
│   ├── app
│   │   ├── ...
│   ├── environments
│   │   ├── environment.prod.ts
│   │   └── environment.ts
│   ├── favicon.ico
│   ├── index.html
│   ├── main.ts
│   ├── polyfills.ts
│   ├── styles.css
│   └── test.ts
├── tsconfig.app.json
├── tsconfig.json
├── tsconfig.spec.json
├── tslint.json
└── .vscode
    └── launch.json
```

**Comment by JosepAlacid** [comment]
There I have it.
In my tree, sorted alphabetically, .vscode is the first folder.
Just updated to angular 9.0.0-rc.10 and issue remains.
It seems kind a caché issue. I need to clear Chrome caché and serve the project again to recover my breakpoints.
My node version is 10.16.3 fyi.

**Comment by HQ92** [comment]
I have a similar issue where I can set a breakpoint and it will get successfully hit the first time I reload the page. But then the line number for the breakpoint in the panel will change to a line that does not exist within the file once it has been hit. Clicking the button to disable and enable all breakpoints again then seems to push vs code into displaying the breakpoints in the correct places again for some reason?

The browser devtools seem to navigate and use the sourcemaps correctly but vs code tries to show me the actual files on the disk but is going wrong slightly somewhere?

[scripts.txt](https://github.com/microsoft/vscode-chrome-debug/files/4233470/scripts.txt)

**Comment by roblourens** [comment]
Would really appreciate if anyone can test their issue with the new JS debugger - https://code.visualstudio.com/updates/v1_42#_new-javascript-debugger

**Comment by rocknet** [comment]
@roblourens, I'm late joining the issue, but I found it by experiencing 
`Error: Set breakpoints request timed out
    at Timeout._onTimeout (c:\Users\crock\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\utils.js:96:24)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)`
while trying to debug an Office Add-In ([Excel custom function using office-js](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-debugging)).  I installed the nightly JS debugger, reloaded VSCode, and added `"debug.javascript.usePreview": true` to my laugh.json configuration.  I still experience the error above and it doesn't break.  I'm not sure how to even tell I'm using the new debugger though, as the lines pasted above don't seem to indicate using a new JS debugger version - I guess maybe they wouldn't.

Please let me know if I'm glomming onto the wrong issue.  Though the app is being served by the node dev server, it's client-side debugging I'm trying to do.  I should point out this is not an Angular app in the office add-in, just based on [office.js 1.1](https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js)

**Comment by roblourens** [comment]
@rocknet I don't know anything about Office addins, are you actually using the vscode chrome debug extension to debug them?

**Comment by rocknet** [comment]
Yes.  The new office add-ins are web apps that run in a browser in a sandbox, the docs for debugging have you use VSCode (link above).  The error I posted I experienced during a debug session of the office add-in.

**Comment by rocknet** [comment]
Update: I've found with the basic sample from the yeoman generator I was able to get VSCode debugging to work.  I plan on diffing the projects to see if I can determine why our project has the breakpoint timeout issue.  If I discover anything potentially useful to this issue, I'll post it here.

**Comment by jayarjo** [comment]
My breakpoints started to misbehave after I set `disableNetworkCache` to `false` in the `launch.json`.

**Comment by hemmoleg** [comment]
What happens for me is that any breakpoint I have set is ignored after hot reloading. However, after setting a new breakpoint anywhere, the new breakpoint and the old ones work again.
Also checking "uncaught exceptions" in vs code breakpoint settings doesnt work at all. Only "All exceptions" does work, but that is a setting which isnt realy useable.

**Comment by MCKRUZ** [comment]
> Update: I've found with the basic sample from the yeoman generator I was able to get VSCode debugging to work. I plan on diffing the projects to see if I can determine why our project has the breakpoint timeout issue. If I discover anything potentially useful to this issue, I'll post it here.

@rocknet I tried the basic yeoman generator, I still get this error.  Can you post your working instance on github?

**Comment by rocknet** [comment]
@MCKRUZ This was a while back, and I had a very specific case of trying to debug an office-js Excel custom function add-in running a React app, pretty different from OP.  IIRC, I think things started to get messed up as soon as I put async calls in.  I think it had more to do with the runtime office-js was using.  They have updated their runtime and are supposed to have a better debugging story now.  Sorry I can't help more, good luck.

**Comment by roblourens** [comment]
This may work with the new debugger. If not, please file an issue at http://github.com/microsoft/vscode-js-debug/
